dev:
	pnpm dev

build:
	pnpm build

test:
	pnpm test

lint:
	pnpm lint && pnpm check

format:
	pnpm format

setup:
	pnpm install && pnpm exec playwright install chromium

.PHONY: dev build test lint format setup
